Silicon_WebApp/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Silicon_WebApp.Entites;

namespace Silicon_WebApp.Controllers
{
	[Authorize]
	public class CoursesController : Controller
	{

		public async Task<IActionResult> Index()
		{
			using var http = new HttpClient();
			var response = await http.GetAsync("https://localhost:7030/api/courses");
			var json = await response.Content.ReadAsStringAsync();
			var data = JsonConvert.DeserializeObject<IEnumerable<CourseEntity>>(json);
			if (data != null)
			{
				return View(data);
			}
			else
			{
				return RedirectToAction("Index", "NotFound");
			}
		}
	}
}

Silicon_WebApp/Controllers/SubscriberController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Silicon_WebApp.Entites;
using Silicon_WebApp.ViewModels;
using System.Net.Http.Headers;
using System.Text;

namespace Silicon_WebApp.Controllers;

public class SubscriberController : Controller
{
	public IActionResult Index()
	{
		return View(new SubscribeViewModel());
	}

	[HttpPost]
	public async Task<IActionResult> Index(SubscribeViewModel viewModel)
	{
		
			if (ModelState.IsValid)
			{
				using var http = new HttpClient();

				var url = $"https://localhost:7030/api/subscriber?email={viewModel.Email}";
				var request = new HttpRequestMessage(HttpMethod.Post, url);


				var response = await http.SendAsync(request);
				if (response.IsSuccessStatusCode)
				{
				viewModel.IsSubscribed = true;
				TempData["IsSubscribed"] = "You are now Subscribed";
				return Redirect(Url.Action("Index", "Home") + "#signup-section");
			}
			TempData["IsSubscribed"] = "Subscription failed";
			return Redirect(Url.Action("Index", "Home") + "#signup-section");
		}
		return Redirect(Url.Action("Index", "Home") + "#signup-section");

	}
}

Silicon_WebApp/Views/Shared/_CookieConsent.cshtml
@if (Context.Request.Cookies["CookieConsent"] == null)
{
	<div id="cookie-consent" class="alert alert-primary fixed-bottom">
		<div class="container">
			<span>This website uses cookies to improve the user experience</span>
			<button class="btn btn-theme" onclick="acceptCookieConsent()">OK</button>
		</div>
	</div>

	<script>
		function acceptCookieConsent() {
			document.getElementById('cookie-consent').style.display = 'none'

			fetch('@Url.Action("CookieConsent", "Settings")', {
				method: 'POST',
				headers: {
					'X-Requested-With': 'XMLHttpRequest'
				}
			})
		}
	</script>

}

Silicon_WebApp/Views/Shared/_Layout.cshtml
@using Silicon_WebApp.ViewModels
@{
	var themeMode = Context.Request.Cookies["ThemeMode"] ?? "light";
	var isDark = (themeMode == "dark") ? true : false;

	var user = await UserManager.GetUserAsync(User);
}


<!DOCTYPE html>
<html lang="sv-se" class="@themeMode">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width" , initial-scale="1.0" />
	<script defer src="https://kit.fontawesome.com/41c8b474e2.js" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	<link rel="icon" href="~/favicon-32x32.png">

	@if (!string.IsNullOrWhiteSpace(ViewData["Title"]?.ToString()))
	{
		<title>@ViewData["Title"] - Silicon</title>
	}
	else
	{
		<title>Silicon</title>
	}


</head>
<body>

	<div class="wrapper">
		
		<header>
			<div class="container">
				<a id="logo" asp-controller="Home" asp-action="Index">
					<img src="~/images/logos/@(isDark ? "logo-dark.svg" : "logo-light.svg")" alt="" />
				</a>
				<button onclick="toggleMenu()" class="btn-mobile">
					<i class="fa-regular fa-bars"></i>
				</button>
				<div id="menu">
					<nav>
						<a class="menu-link" asp-controller="Home" asp-fragment="overview">Overview</a>
						@if (User.Identity!.IsAuthenticated)
						{
							<a class="menu-link" asp-controller="Courses" asp-fragment="Index">Courses</a>
						}
						else
						{
							<a class="menu-link" asp-controller="Home" asp-fragment="features">Features </a>
						}
						<a class="menu-link" asp-controller="NotFound" asp-action="Index">Contact</a>
					</nav>
				</div>

				<div class="btn-switch">
					<label>Light</label>
					<label class="switch" for="switch-mode">
						<input type="checkbox" id="switch-mode" checked="@isDark" />
						<span class="slider round"></span>
					</label>
					<label>Dark</label>
				</div>

				<div class="account-buttons">
					@if (User.Identity.IsAuthenticated)
					{
						<div class="profile-link">
						<a asp-controller="Account" asp-action="Index"><img src="~/uploads/@user!.ProfileImageUrl" alt="Profile image"/></a>
						</div>
					}
					else
					{
						<a class="btn-gray" asp-controller="Auth" asp-action="Login"><i class="fa-solid fa-right-to-bracket"></i><span>Sign In</span></a>
						<a class="btn-theme" asp-controller="Auth" asp-action="Register"><i class="fa-regular fa-user"></i><span>Sign Up</span></a>
					}
				</div>

				<div id="account-buttons" class="hide">
				</div>

			</div>

		</header>
	
		<main>
			@RenderBody()
		</main>
		<footer>
			<div class="container">
				<div class="@((ViewContext.RouteData.Values["Controller"]!.ToString() == "Auth") ? "d-none" : "social-media")">
					<a class="btn-social" href="#"><i class="fa-brands fa-facebook"></i> </a>
					<a class="btn-social" href="#"><i class="fa-brands fa-square-x-twitter"></i> </a>
					<a class="btn-social" href="#"><i class="fa-brands fa-instagram"></i> </a>
					<a class="btn-social" href="#"><i class="fa-brands fa-youtube"></i> </a>
				</div>
				<p><strong> &copy; @DateTime.Now.Year Silicon. All rights reserved.</strong><span> Pulvinar urna condimentum amet tempor, ornare integer. Lorem odio justo malesuada suspendisse viverra aliquet quisque turpis non. Feugiat in odio non nunc ornare consectetur.</span></p>
			</div>
		</footer>
	</div>
	<script defer src="~/js/site.js" asp-append-version="true"></script>
	<script defer src="~/js/validation.js" asp-append-version="true"></script>
	<script defer src="~/js/themeswitcher.js" asp-append-version="true"></script>

	<partial name="_CookieConsent" />

</body>
</html>

Silicon_WebApp/Views/Shared/_headerPartial.cshtml
@using Silicon_WebApp.ViewModels
@{
	var themeMode = Context.Request.Cookies["ThemeMode"] ?? "light";
	var isDark = (themeMode == "dark") ? true : false;
	@model AccountDetailsViewModel

}

		

Silicon_WebApp/Views/Shared/_newsletterPartial.cshtml
@using Silicon_WebApp.ViewModels
@model SubscribeViewModel

<section id="signup-section">
	<div class="newsletter">
		<div class="container">
			<div class="title">
				<h1>Don't want to Miss Anything?</h1>
				<img src="~/images/arrows.svg" alt="decorative arrows" />
			</div>



			<form asp-action="Index" asp-controller="Subscriber" method="post">
				<div class="newsletter-checkbox-group">
					<h4 id="title">Sign up for Newsletters</h4>
					<label>
						<input id="newsletter" type="checkbox" name="Daily Newsletter" />
						Daily Newsletter
					</label>
					<label>
						<input id="updates" type="checkbox" name="Advertising Updates" />
						Advertising Updates
					</label>
					<label>
						<input id="review" type="checkbox" name="Week in Review" />
						Week in Review
					</label>
					<label>
						<input id="updates" type="checkbox" name="Event Updates" />
						Event Updates
					</label>
					<label>
						<input id="startups" type="checkbox" name="Startups Weekly" />
						Startups Weekly
					</label>
					<label>
						<input id="podcasts" type="checkbox" name="Podcasts" />
						Podcasts
					</label>
				</div>
				<div class="email-button">
					<div class="input-with-icon">
						<i class="fa-regular fa-envelope"></i>
						<input asp-for="@Model.Email" type="email" placeholder="Your Email" />
					</div>
					<div class="subscribe-button">
						<button type="submit" class="btn-theme">Subscribe*</button>
					</div>
				</div>

				<p>* Yes, I agree to the <a href="#">terms</a> and <a href="#">privacy</a> policy.</p>
			</form>
			@if (Model.IsSubscribed)
			{
				<div class="alert alert-primary">You are subscribed</div>
			}
		</div>
	</div>
</section>